#!/usr/bin/env bash
# attach the container(s) to logger
set -eo pipefail
APP="$1"; PORT="$2"
APP_ROOT="$DOKKU_ROOT/$APP"
APP_PS="$APP_ROOT/PS"

while read line; do
  NAME=${line%%=*}
  NUM=${line#*=}
  for ((i=1; i<=NUM; i++)); do
    sudo start dokku-syslog APP=$APP NAME=$NAME SEQ=$i > /dev/null || true # dont fail if already running
  done
done < $APP_PS